-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.answer
(
    id bigint NOT NULL,
    answer text COLLATE pg_catalog."default" NOT NULL,
    id_question bigint NOT NULL,
    is_right boolean NOT NULL,
    CONSTRAINT answer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.question
(
    id bigint NOT NULL,
    question text COLLATE pg_catalog."default" NOT NULL,
    id_test bigint NOT NULL,
    CONSTRAINT question_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.skill
(
    id bigint NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT skill_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.skill_vacancy
(
    id_vacancy bigint NOT NULL,
    id_skill bigint NOT NULL,
    CONSTRAINT skill_vacancy_pkey PRIMARY KEY (id_vacancy, id_skill)
);

CREATE TABLE IF NOT EXISTS public.test
(
    id bigint NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    average_passing_time text COLLATE pg_catalog."default",
    id_skill bigint,
    CONSTRAINT test_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tokens
(
    id bigint NOT NULL DEFAULT nextval('tokens_id_seq'::regclass),
    token text COLLATE pg_catalog."default" NOT NULL,
    user_id bigint NOT NULL DEFAULT nextval('tokens_user_id_seq'::regclass),
    CONSTRAINT tokens_pk PRIMARY KEY (id),
    CONSTRAINT tokens_uk UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.user_skill
(
    id_user bigint NOT NULL,
    id_skill bigint NOT NULL,
    proficiency_level integer NOT NULL,
    CONSTRAINT user_skill_pkey PRIMARY KEY (id_user, id_skill)
);

ALTER TABLE "users"
    RENAME TO "user";

CREATE TABLE IF NOT EXISTS public.vacancy
(
    id bigint NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    grade text COLLATE pg_catalog."default",
    date timestamp without time zone,
    description text COLLATE pg_catalog."default",
    CONSTRAINT vacancy_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.answer
    ADD CONSTRAINT question_fk FOREIGN KEY (id_question)
        REFERENCES public.question (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.question
    ADD CONSTRAINT test_fk FOREIGN KEY (id_test)
        REFERENCES public.test (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE IF EXISTS public.skill_vacancy
    ADD CONSTRAINT skill_fk FOREIGN KEY (id_skill)
        REFERENCES public.skill (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.skill_vacancy
    ADD CONSTRAINT vacancy_fk FOREIGN KEY (id_vacancy)
        REFERENCES public.vacancy (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.test
    ADD CONSTRAINT skill_fk FOREIGN KEY (id_skill)
        REFERENCES public.skill (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID;


ALTER TABLE "tokens"
    RENAME TO "token";


ALTER TABLE IF EXISTS public.user_skill
    ADD CONSTRAINT skill_fk FOREIGN KEY (id_skill)
        REFERENCES public.skill (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_skill
    ADD CONSTRAINT user_fk FOREIGN KEY (id_user)
        REFERENCES public.user (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION;

END;